name: Build & Publish custom Cube image

on:
  push:
    branches: [ pre_agg_obervables ]   # ajoute main/master si tu veux
  workflow_dispatch:

concurrency:
  group: docker-publish-${{ github.ref }}
  cancel-in-progress: true

jobs:
  verify:
    name: Verify monorepo build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node (20.x) + Yarn cache
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Install deps
        run: yarn install --frozen-lockfile

      # Affiche clairement les erreurs de build (lerna stream)
      - name: Build all packages
        run: yarn lerna run build --stream --no-prefix

  docker:
    name: Build & Push Docker (amd64)
    needs: verify
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      IMAGE_REPO: ${{ secrets.DOCKERHUB_USERNAME }}/cube-custom

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker metadata (tags & labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: docker.io/${{ env.IMAGE_REPO }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha
          labels: |
            org.opencontainers.image.source=${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.title=Cube custom (from source)
            org.opencontainers.image.url=https://github.com/${{ github.repository }}

      - name: Build & Push (amd64)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: packages/cubejs-docker/dev.Dockerfile
          platforms: linux/amd64
          push: true
          provenance: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}
